# Generated by Django 3.1.1 on 2020-11-06 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(related_name='_account_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(related_name='_account_following_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
