# Generated by Django 3.1.1 on 2020-11-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_likers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
